language: node_js
node_js:
- stable
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/
  target-branch: gh-pages
  on:
    branch: master
